name: Architecture Decision Record
description: A document that captures an important architectural decision made along with its context and consequences.
title: "[ADR]: "
labels: ["adr"]
assignees:
  - errbufferoverfl
body:
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: What is the status of this ADR?
      options:
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superseded
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What is the issue that we're seeing that is motivating this decision or change?
  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: What is the change that we're proposing and/or doing?
  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      description: What becomes easier or more difficult to do because of this change?
