"""Fixes connection between Connections and Users


Revision ID: 81185b98fdf7
Revises: cc8f8e1173b3
Create Date: 2025-02-14 14:13:28.992147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81185b98fdf7'
down_revision = 'cc8f8e1173b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_owners',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['authentication_connection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.fs_uniquifier'], ),
    sa.PrimaryKeyConstraint('user_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_owners')
    # ### end Alembic commands ###
