"""Add support for SAML configuration

Revision ID: cc8f8e1173b3
Revises: 84cee9706b8c
Create Date: 2025-02-14 14:09:40.290635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8f8e1173b3'
down_revision = '84cee9706b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authentication_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authentication_connection_connection_id'), ['connection_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_authentication_connection_id'), ['id'], unique=False)

    op.create_table('authentication_connection_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration_blob', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['authentication_connection.connection_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authentication_connection_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authentication_connection_configuration_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authentication_connection_configuration_id'), ['id'], unique=False)

    op.create_table('authentication_connection_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('metadata_blob', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['authentication_connection.connection_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authentication_connection_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authentication_connection_metadata_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authentication_connection_metadata_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_connection_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authentication_connection_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_authentication_connection_metadata_connection_id'))

    op.drop_table('authentication_connection_metadata')
    with op.batch_alter_table('authentication_connection_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authentication_connection_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_authentication_connection_configuration_connection_id'))

    op.drop_table('authentication_connection_configuration')
    with op.batch_alter_table('authentication_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authentication_connection_id'))
        batch_op.drop_index(batch_op.f('ix_authentication_connection_connection_id'))

    op.drop_table('authentication_connection')
    # ### end Alembic commands ###
